Controller: define an actual function for entry point
The automagic setuptools entry_points console_scripts need to
call a real function to work, the current wrappers fail with:
ImportError: <module 'Shine.Controller' from '/usr/lib/python2.7/site-packages/Shine/Controller.pyc'> has no 'main' attribute


Fixes: b398a56a54b0 ("packaging: lots of cleaning of shine distribution")
Change-Id: I6886313e1026bbfc018fa068d8be5bad4727624e